# Generated by Django 6.0.1 on 2026-01-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_match_match_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='code',
            field=models.CharField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
