# Generated by Django 6.0.1 on 2026-01-22 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_competition_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_shot_time', models.FloatField()),
                ('end_shot_time', models.FloatField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_timings', to='backend.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_timings', to='backend.team')),
            ],
            options={
                'ordering': ['match', 'start_shot_time'],
            },
        ),
    ]
