# Generated by Django 6.0.1 on 2026-01-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_shottiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='blue_1_climb',
            field=models.CharField(choices=[('None', 'None'), ('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_2_climb',
            field=models.CharField(choices=[('None', 'None'), ('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_3_climb',
            field=models.CharField(choices=[('None', 'None'), ('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='red_1_climb',
            field=models.CharField(choices=[('None', 'None'), ('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='red_2_climb',
            field=models.CharField(choices=[('None', 'None'), ('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='red_3_climb',
            field=models.CharField(choices=[('None', 'None'), ('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3')], default='None', max_length=10),
        ),
    ]
